bounty claim and bounty claim detail page
OpenUnited/platform pull request #216
Opened 2024-04-13 10:26 UTC by endalkh

2024-04-13 10:41 UTC, dogukanteber requested changes
Let's have a separate PR for changing the status names since this is a breaking change.

2024-04-13 10:41 UTC, dogukanteber commented on talent/models.py
> +
Let's remove `ClaimStatus` class and have `CLAIM_TYPE` variable in `BountyClaim` class. Also, let's capitalize the constant variables such as `REQUESTED.`

2024-04-13 10:41 UTC, dogukanteber commented on talent/models.py
> +        default=ClaimStatus.Requested,
Keep the name `kind`. We don't want anything to break.

2024-04-13 10:52 UTC, endalkh commented on talent/models.py
> +
Capitalize the variable makes sense, why do you want to remove the class? it removes duplicates.

2024-04-13 11:14 UTC, dogukanteber commented on talent/models.py
> +
To be consistent throughout the codebase. Also, every time we have to type `ClaimStatus` when we want to reference one of its variables like `BountyClaim.ClaimStatus. REQUESTED`. Instead, `BountyClaim.REQUESTED` is shorter.

2024-04-13 11:19 UTC, endalkh commented on talent/models.py
> +
BountyClaim.ClaimStatus.REQUESTED is just one line of code, See how many lines it takes on each class and has works on the templates. If you want to change the variables inside the class, you should also update the template. 

<img width="858" alt="Screenshot 2024-04-13 at 2 16 52 PM" src="https://github.com/OpenUnited/platform/assets/54709447/83411349-4a31-4c49-8ac8-e43e300bd563">

2024-04-13 11:29 UTC, dogukanteber commented on talent/models.py
> +
It is one line of code but every time we have to mention the status we'd have to repeatedly type `ClaimStatus`as well like this:

```python
filter_data["bountyclaim__status__in"] = [
       BountyClaim.ClaimStatus.Completed,
       BountyClaim.ClaimStatus.Granted,
]
```

I know it's just a small thing but we should do it this way to avoid duplication later and to be consistent with the other models.

2024-04-13 11:54 UTC, endalkh commented on talent/models.py
> +
We discussed this with @adrianmcphee and I don't know why you hate the above implementation. 

With your approach

1. I should declare all the variables with int value.
2. Then declare a tuple variable and  map those variables with a tuple
3. Then declare those variables again everywhere in the templates. 
4. Then get the value like this: {{TASK_TYPES[bounty.status ] }}

The above approach has many steps and is a waste of memories.  I can change it as it was if you need the old approach even if I don't believe it is better.

2024-04-13 12:16 UTC, dogukanteber commented on talent/models.py
> +
I don't hate this implementation. I want to have consistency in the codebase. I didn't consider declaring the variables in the templates. I would pass them as a context although the current implementation is not like that.

If you want to keep this change, then at least change the name `ClaimStatus` to `Status` and capitalize the variable names.

2024-04-14 11:42 UTC, adrianmcphee commented
I'm going to merge this to get it done

2024-04-14 11:42 UTC, merged