Cast vote for idea
OpenUnited/platform pull request #258
Opened 2024-05-13 13:35 UTC by sachintom999

- Added capability for a **logged in user** to vote / unvote  for an idea
- Without logging in, the vote button is not visible

### Testing

**Case : logged in user**

![13may](https://github.com/OpenUnited/platform/assets/62328681/35eeb8e2-1e98-4177-8455-b3fb41ea0ec8)

**_Case: user without authentication_**

![image](https://github.com/OpenUnited/platform/assets/62328681/ccaef210-ed83-4fa8-be17-8d4fe49f453e)

@adrianmcphee , I will raise a separate PR for unit tests for the above functionality

2024-05-13 17:37 UTC, endalkh requested changes
Great job @sachintom999

2024-05-13 17:37 UTC, endalkh commented on product_management/views.py
> +            )
I think you can use `idea.voted_users.count()` instead of  `len(idea.voted_users)`

`ideas_with_votes.append(
                {
                    "idea_obj": idea,
                    "num_votes": idea.voted_users.count(),
                    "user_has_voted": user_id in idea.voted_users,
                }
            )`

2024-05-13 17:37 UTC, endalkh commented on product_management/views.py
> +        user_id = self.request.user.id
I think this could fail for unauthenticated. I suggest to to check the user has logged in or not, if not I would redirect to the log-in or signup page. What do you think @adrianmcphee

2024-05-13 17:37 UTC, endalkh commented on product_management/views.py
> +        id=pk, voted_users__contains=[user_id]
I think you can use `__in` instead of `__contains`
 user_has_voted = Idea.objects.filter(voted_users__in=[user_id]

2024-05-13 17:37 UTC, endalkh commented on product_management/views.py
> +        idea.voted_users.append(user_id)
I think you can also use add instead of append  `idea.voted_users.add(user_id)`

2024-05-13 17:37 UTC, endalkh commented on product_management/templates/product_management/product_idea_list.html
> +        {% if request.user.is_authenticated %}
Oh, Great!, I thought you didn't handle unauthenticated users.

2024-05-13 17:37 UTC, endalkh commented on product_management/views.py
> +    return HttpResponse(str(len(idea.voted_users)))
I'm just curious, why did you convert it to a string? Could you use idea.voted_users.count() instead?

2024-05-13 18:47 UTC, adrianmcphee commented on product_management/views.py
> +        user_id = self.request.user.id
yes, good idea - I agree that it needs to handle unauthenticated users well

2024-05-14 17:23 UTC, adrianmcphee commented
@endalkh should we perhaps merge this as is, or are your suggestions important enough that they should be addressed?

2024-05-15 01:11 UTC, sachintom999 commented
> @endalkh should we perhaps merge this as is, or are your suggestions important enough that they should be addressed?

@endalkh - Thanks for the review comments. 

@adrianmcphee, 
As per our discussion, though adding the field `voted_users` is simpler, on further reading, your idea of  adding a new model (called `IdeaVote` ) is more robust and prevents data corruption in certain cases.
I am implementing that approach. All the comments above will be addressed when I push the latest changes.
I will do that in some time.

2024-05-15 02:22 UTC, sachintom999 commented
@adrianmcphee  @endalkh  ,
the pipeline is failing because of conflicting migrations
![image](https://github.com/OpenUnited/platform/assets/62328681/00b715c5-876a-4d23-8621-3fefccfe4559)

I tried pulling the latest main branch into this feature branch and for me , it says `No conflicts detected to merge.`

Could you please try at your end. Thanks

2024-05-15 06:32 UTC, endalkh commented
@sachintom999 can you please pull the last changes and run migration merge

'python manage-py nakemigrations --merge'

2024-05-15 06:33 UTC, endalkh commented
Thank you @sachintom999

2024-05-15 06:40 UTC, sachintom999 commented
@endalkh 
I already did that , but it says 
No conflicts detected to merge

2024-05-15 07:16 UTC, sachintom999 commented
@endalkh , sorry. My fork was not upto date. Hence the above issues.
Fixed all issues now.

2024-05-15 21:58 UTC, endalkh approved these changes

2024-05-15 21:58 UTC, endalkh commented on security/models.py
>          db_table = "black_listed_usernames"
I like this, but most of the models use default naming, which is the public schema plus the name of the model: <public.name_of_the_model>. To maintain consistency, I recommend sticking with the default table naming.

2024-05-15 21:58 UTC, endalkh commented on security/models.py
> +    voted_at = models.DateTimeField(auto_now_add=True)
I think you can use created_at here. You can override  `TimeStampMixin`

2024-05-16 04:44 UTC, sachintom999 commented on security/models.py
>          db_table = "black_listed_usernames"
@endalkh , this code was already present in the file.
I did not modify this as part of my changes

2024-05-16 04:51 UTC, sachintom999 commented on security/models.py
> +    voted_at = models.DateTimeField(auto_now_add=True)
done

2024-05-16 06:49 UTC, endalkh commented on security/models.py
>          db_table = "black_listed_usernames"
Okay Sorry!

2024-05-16 06:50 UTC, endalkh commented on security/models.py
> +    voted_at = models.DateTimeField(auto_now_add=True)
Thank you!

2024-05-16 08:23 UTC, merged