e2e tests: Claim Bounty
OpenUnited/platform pull request #313
Opened 2024-06-03 09:06 UTC by sachintom999

**Changes**
- Refactored `BaseE2ETest` to be reused across all the tests which requires login. Inheriting `BaseE2ETest` will automatically creates a test user and login the test user into the application. Any such test only need to handle the functionality and checks after login .
- Because of the above, refactored `e2e/test_login.py`
- Added tests for Claim Bounty functionality

**Testing**
![test_clain_bounty](https://github.com/OpenUnited/platform/assets/62328681/86a1ff5c-ec48-44d4-8ae5-5e8a338d76a8)

2024-06-03 10:07 UTC, endalkh requested changes

2024-06-03 10:07 UTC, endalkh commented on e2e/base.py
> +        )
Could you please use existing fixtures or create a new one in `conftest.py`?

2024-06-03 10:07 UTC, endalkh commented on e2e/test_claim_bounty.py
> +        )
Could you please use existing fixtures or create a new one in conftest.py?

2024-06-09 08:32 UTC, adrianmcphee commented
@sachintom999 are the changes requested by @endalkh sufficiently clear?

2024-06-09 08:45 UTC, sachintom999 commented
> @sachintom999 are the changes requested by @endalkh sufficiently clear?

@adrianmcphee , yes it clear . I got occupied and didnt get a chance to address it . Will push the changes in a couple of days .

2024-06-10 08:18 UTC, endalkh requested changes

2024-06-12 04:14 UTC, sachintom999 commented
@endalkh, thanks for your review comments. Really appreciate it.
Before I make the changes as per your last comments, I am planning to get the test pass in the pipeline. 
It is passing in my local, but somehow failing in the pipeline . 
Error - The  assertion for `BountyClaim` record , on clicking `Claim Bounty` button is failing.
I tried increasing the delay between the click and assertion , to make sure enough time for the db operation (  `BountyClaim` record creation) to complete. 

If you have bandwidth, could you please try at your end as well  ?

2024-06-12 08:30 UTC, endalkh commented
> @endalkh, thanks for your review comments. Really appreciate it. Before I make the changes as per your last comments, I am planning to get the test pass in the pipeline. It is passing in my local, but somehow failing in the pipeline . Error - The assertion for `BountyClaim` record , on clicking `Claim Bounty` button is failing. I tried increasing the delay between the click and assertion , to make sure enough time for the db operation ( `BountyClaim` record creation) to complete.
> 
> If you have bandwidth, could you please try at your end as well ?

Hey @sachintom999, Thank you, Sure! I'll check that.

2024-06-13 03:24 UTC, sachintom999 commented
@endalkh thanks for the input. I will check that and get back.

2024-06-20 13:31 UTC, merged