Add tailwindcss standalone support
OpenUnited/platform pull request #56
Opened 2023-09-26 07:08 UTC by FJLendinez

2023-09-26 10:54 UTC, adrianmcphee commented
@dogukanteber good to merge?

2023-09-26 10:54 UTC, adrianmcphee commented
thank you very much @FJLendinez !

2023-09-27 09:32 UTC, dogukanteber requested changes
Thank you for your PR @FJLendinez. It really helped. There are just minor stuff. If you fix those, we can merge the PR.

2023-09-27 09:32 UTC, dogukanteber commented on templates/base_html.html
> +    <script src="{{ static('styles/tailwind.css') }}"></script>
This line should be `<link rel="stylesheet" href="{{ static('styles/tailwind.css') }}">`.

Additionally, we have another `base.html` file in the security app. Could you add this line to that template as well?

Path: `security/templates/security/base_security.html`

2023-09-27 09:32 UTC, dogukanteber commented on tailwind.config.js
> +  content: ['./templates/*.html', './templates/*/*.html', './*/templates/*/*.html'],
We also have subdirectories under the templates files such as `talent/templates/talent/partials/gray_star.html`. Should we include that pattern in content as well by adding `./*/templates/*/*/*.html`?

2023-09-30 08:48 UTC, FJLendinez commented on tailwind.config.js
> +  content: ['./templates/*.html', './templates/*/*.html', './*/templates/*/*.html'],
Instead of adding this pattern, I add a generic pattern using `**`

As you can see in the [documentation](https://tailwindcss.com/docs/content-configuration)

> Use `**` to match zero or more directories

2023-09-30 08:48 UTC, FJLendinez commented
@dogukanteber can you check again?

2023-09-30 09:03 UTC, dogukanteber approved these changes
It works now. Thank you ❤️

2023-09-30 09:04 UTC, merged