Fix Product Update View
OpenUnited/platform pull request #86
Opened 2023-10-17 20:44 UTC by sachintom999

## Background

 - The Product Update View is currently not working
 
### Issues
- It does not allows to save the changes to an existing product without update the product name. ( due to checking slug )
- if we tries to save by updating the product name, it errors out with null constraint error for "object_id" field
- It is demonstrated as below -

![before-fix](https://github.com/OpenUnited/platform/assets/62328681/35ea48d4-f639-49e4-82a4-0fb6f6e2e844)

### Solution
- the first issue can be solved by skipping the slug checking in the `clean_name()` method in the `ProductForm`
- the fix of the second issue ( updating the Product ) has a lot of moving parts:
     - introduce the `clean()` method in `ProductForm`
     - move the `owner` validation from `CreateProductView` to this `clean` method
     - allowing user to select either `organisation` or the `user` itself as the owner
     - render organisation/user value in the update view template from the db
     - throw an error if user selects both organisation and himself OR dont select any of the two
     - render the above errors in the template

### Changes
- `product_management/views.py`
- `product_management/forms.py`
- `product_management/templates/product_management/forms/product_form.html`

### Testing 
- After the changes the testing has been done for the below scenarios
    - Trying to create a new product 
        - without any owner  -> resulting in error :  `You have to select an owner`
        - with both `organisation` and `user` both selected -> resulting in error : `A product cannot be owned by a person and an organisation`
    - Successfully creating a new product
    - Updating the newly created product , without updating product name ( solving the slug checking issue)
    - Updating the owner to  a) an organisation  b) user. Both rendering correctly in the template after the update
    - In the update view, saving the product without making any changes to the existing field
    - Please find the demo below : 
    
![after-fix](https://github.com/OpenUnited/platform/assets/62328681/72ebbcb7-ca0f-448e-8d8c-9fa8ed827d4b)

2023-10-17 21:13 UTC, dogukanteber commented on product_management/forms.py
>          required=False,
Can you add the following here:

`TODO: We should not get all the organizations here. After the organization hierarchy is constructed, we need to filter based on the current user's organizations.`

2023-10-17 21:14 UTC, dogukanteber requested changes
Perfect job @sachintom999. I have been meaning to make this refactoring but did not know updating is not working. Thank you very much for your contribution.

There are two super minor modifications I want you to make. After that, we can merge it.

2023-10-17 21:20 UTC, dogukanteber commented on product_management/templates/product_management/forms/product_form.html
> +                                <li class="text-xs italic text-red-600 ">Error : {{ error }}</li>
We can also remove the italic class from the class list and  `Error : ` string from the text.

2023-10-18 02:24 UTC, sachintom999 commented
> Perfect job @sachintom999. I have been meaning to make this refactoring but did not know updating is not working. Thank you very much for your contribution.
> 
> There are two super minor modifications I want you to make. After that, we can merge it.

hi @dogukanteber,
Thanks for reviewing 🙂 . I have made the requested changes and pushed.

2023-10-18 07:30 UTC, dogukanteber approved these changes

2023-10-18 07:30 UTC, dogukanteber commented
Awesome. Let's merge it 🚀

2023-10-18 07:30 UTC, merged

2024-05-11 19:58 UTC, adrianmcphee commented
@sachintom999  are you available to help further on OpenUnited? If so please DM me via our Discord server https://discord.com/invite/T3xevYvWey thanks