Added profile picture preview on successful upload
OpenUnited/platform pull request #96
Opened 2023-10-19 05:23 UTC by sachintom999

### Background
- In the user profile page, when a user uploads his profile picture, there is no preview of the uploaded picture. The user is not sure whether the upload is success or not. The uploaded profile picture is getting saved on submit though.

#### Demo
![before-fix](https://github.com/OpenUnited/platform/assets/62328681/534a0d0b-229b-4b82-a10f-a397bb99cab3)

### Solution
- Add an image preview element in the html ( which is not displayed by default ) , but will be visible with the last uploaded image when the image upload is success

*Note :* 
- As per this solution, the `Remove Button` is hidden when user uploads a new picture, to avoid confusion. He can upload a new image to change the first uploaded image.
- The button is shown until he changes the original profile picture.
- Another observation is that, currently in the update profile page, we don't have a way to revert any unsaved text changes, unless he refreshes the page. Something like a `Cancel` button is a potential solution.
- The functionality of the `Remove Button` which deletes the original picture is retained.

### Changes
- `talent/templates/talent/profile_picture.html`

### Testing after fix
![after-fix](https://github.com/OpenUnited/platform/assets/62328681/5dd1f2c3-a4df-4e73-88f4-142190a0f295)

2023-10-19 06:29 UTC, sachintom999 commented on talent/templates/talent/profile_picture.html
> +    <div id="profile-picture-placeholder"
Changed `id` as it is same as the `id` of the `div` in line 1

2023-10-19 09:01 UTC, dogukanteber commented on talent/templates/talent/profile_picture.html
> +        style="display: none;" />
We can remove `style` tag and add `hidden` to the class list

2023-10-19 09:05 UTC, dogukanteber commented on talent/templates/talent/profile_picture.html
> +            imagePreview.style.display = "block"
When we remove the `style` tag above, we should add or remove the `hidden` class from the image tag.

2023-10-19 09:07 UTC, dogukanteber requested changes
Thank you for your contribution @sachintom999. Normally, we avoid using Javascript as much as possible. Instead, we use [Hyperscript](https://hyperscript.org/). However, in this case, using Hyperscript instead of Javascript introduces more complexity, in my opinion.

I just wanted to give you an idea of how we do things.

After you modify the PR according to the comments I just left, we can merge it.

Once again, thank you for your work!

2023-10-20 03:14 UTC, sachintom999 commented
> Thank you for your contribution @sachintom999. Normally, we avoid using Javascript as much as possible. Instead, we use [Hyperscript](https://hyperscript.org/). However, in this case, using Hyperscript instead of Javascript introduces more complexity, in my opinion.
> 
> I just wanted to give you an idea of how we do things.
> 
> After you modify the PR according to the comments I just left, we can merge it.
> 
> Once again, thank you for your work!

hi @dogukanteber ,
Thank you for reviewing. 
Noted your point of using Hyperscript. Will keep in mind in the future PRs.

I have made the requested changes and pushed.

2023-10-20 08:04 UTC, dogukanteber commented
Well done, thanks!

2023-10-20 08:04 UTC, merged